apiVersion: v1
kind: Service
metadata:
  name: to-do-app
  namespace: default
  labels:
    app: to-do-app
spec:
  type: NodePort
  selector:
    app: to-do-app
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30080