services:
  app:
    image: ghcr.io/hosain-ghoraba/todo-list-nodejs:main
    restart: always
    ports:
      - "4000:4000"   
    env_file:
      - .env

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"] 
      interval: 30s
      timeout: 10s
      retries: 3

  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=10 
      - WATCHTOWER_INCLUDE_STOPPED=true


